Repository poiuztrewq1/projlab_holy_oil, pull requests merged in 2021-04, with the labels that each got.

#276 Play game command
  java/src/hu/holyoil/controller/InputOutputController.java
Labels: help wanted, low priority, question

#283 small bugfixes
  java/src/hu/holyoil/controller/InputOutputController.java
  java/src/hu/holyoil/recipe/RobotRecipe.java
  java/src/hu/holyoil/recipe/TeleporterRecipe.java
  java/src/hu/holyoil/storage/PlayerStorage.java
Labels: bug

#287 repository comments
  java/src/hu/holyoil/repository/AbstractBaseRepository.java
  java/src/hu/holyoil/repository/AsteroidRepository.java
  java/src/hu/holyoil/repository/CrewmateRepository.java
  java/src/hu/holyoil/repository/IReadRepository.java
  java/src/hu/holyoil/repository/IReadWriteRepository.java
  java/src/hu/holyoil/repository/MinerRepository.java
  java/src/hu/holyoil/repository/NeighbourBaseRepository.java
  java/src/hu/holyoil/repository/PlayerStorageBaseRepository.java
  java/src/hu/holyoil/repository/ResourceBaseRepository.java
  java/src/hu/holyoil/repository/SettlerRepository.java
  java/src/hu/holyoil/repository/SpaceshipBaseRepository.java
  java/src/hu/holyoil/repository/StorageCapableRepository.java
Labels: documentation

#289 Remove wrongful line in output file
  java/testdir/res_water_evaporates.txt
Labels: bug

#290 Comments
  java/src/hu/holyoil/controller/TurnController.java
  java/src/hu/holyoil/neighbour/Asteroid.java
  java/src/hu/holyoil/neighbour/TeleportGate.java
Labels: documentation

#288 Add CommandHandlers javadocs
  java/src/hu/holyoil/commandhandler/ICommandHandler.java
  java/src/hu/holyoil/commandhandler/addneighbourcommand/AddNeighbourCommandHandler.java
  java/src/hu/holyoil/commandhandler/causesunstormcommand/CauseSunstormCommandHandler.java
  java/src/hu/holyoil/commandhandler/createcommand/AsteroidCreateCommandHandler.java
  java/src/hu/holyoil/commandhandler/createcommand/CoalCreateCommandHandler.java
  java/src/hu/holyoil/commandhandler/createcommand/CreateCommandHandler.java
  java/src/hu/holyoil/commandhandler/createcommand/IronCreateCommandHandler.java
  java/src/hu/holyoil/commandhandler/createcommand/PlayerStorageCreateCommandHandler.java
  java/src/hu/holyoil/commandhandler/createcommand/RobotCreateCommandHandler.java
  java/src/hu/holyoil/commandhandler/createcommand/SettlerCreateCommandHandler.java
  java/src/hu/holyoil/commandhandler/createcommand/TeleportpairCreateCommandHandler.java
  java/src/hu/holyoil/commandhandler/createcommand/UfoCreateCommandHandler.java
  java/src/hu/holyoil/commandhandler/createcommand/UraniumCreateCommandHandler.java
  java/src/hu/holyoil/commandhandler/createcommand/WaterCreateCommandHandler.java
  java/src/hu/holyoil/commandhandler/docommand/CraftDoCommandHandler.java
  java/src/hu/holyoil/commandhandler/docommand/DoCommandHandler.java
  java/src/hu/holyoil/commandhandler/docommand/DrillDoCommandHandler.java
  java/src/hu/holyoil/commandhandler/docommand/LookAroundDoCommandHandler.java
  java/src/hu/holyoil/commandhandler/docommand/MineDoCommandHandler.java
  java/src/hu/holyoil/commandhandler/docommand/MoveDoCommandHandler.java
  java/src/hu/holyoil/commandhandler/docommand/PlaceResourceDoCommandHandler.java
  java/src/hu/holyoil/commandhandler/docommand/PlaceTeleportgateDoCommandHandler.java
  java/src/hu/holyoil/commandhandler/explodeasteroidcommand/ExplodeAsteroidCommandHandler.java
  java/src/hu/holyoil/commandhandler/loadcommand/LoadCommandHandler.java
  java/src/hu/holyoil/commandhandler/statecommand/StateCommandHandler.java
Labels: documentation

#294 IIdentifiable comments
  java/src/hu/holyoil/IIdentifiable.java
Labels: documentation

#295 Add docks by beni
  java/src/hu/holyoil/controller/GameState.java
  java/src/hu/holyoil/controller/InputOutputController.java
Labels: documentation

#267 Add useful tips in Readme
  java/README.md
Labels: documentation

#304 gui seq diagrams
  uml/class_diagrams/gui_class.plantuml
  uml/gui_seq_diagrams/default.plantuml
  uml/gui_seq_diagrams/draw.plantuml
  uml/gui_seq_diagrams/init_menuframe.plantuml
  uml/gui_seq_diagrams/mouseclicked_environmentpanel.plantuml
  uml/gui_seq_diagrams/mouseclicked_inventorylistpanel.plantuml
  uml/gui_seq_diagrams/update_environmentpanel.plantuml
  uml/gui_seq_diagrams/update_gameframe.plantuml
  uml/gui_seq_diagrams/update_inventorylistpanel.plantuml
  uml/gui_seq_diagrams/update_playerlist.plantuml
Labels: documentation, sequence diagram
